apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shelfshare-postgres
  namespace: shelfshare-localprod
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: ">=18.1.13"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: shelfshare-localprod
  valuesFrom:
    - kind: Secret
      name: shelfshare-postgres-values
      valuesKey: values.yaml
