apiVersion: ENC[AES256_GCM,data:JCE=,iv:d2SIM6ze2gZBugKn+GgLDUgU6ELJF8T+6uNSOuWPEng=,tag:cgjI0GUWRTmC0Mz7NB+8jQ==,type:str]
kind: ENC[AES256_GCM,data:/Ony4ExL,iv:fR8oUqMPS0bYDa9JXZrZiBHePRv3iBwK04jSWEI3myY=,tag:tchzV6RNGwLPpiCzuryjBA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:iPtHKVO8krtw1FkrgCPcsFW8GwyvytRIgws=,iv:2Pcqipnz0/S/nAdVvN1tiMoH+R0dVNbYsd91EYBKJyc=,tag:3mCmK5mP720uJETZYYVl4w==,type:str]
  namespace: ENC[AES256_GCM,data:hQoGRTx20+/dR2vcHao2uH6n5DU=,iv:s5gIu09XJyq2kTVQroqz1YCRxEY0xQBEK5DF3UOOwVk=,tag:zUfnMnOceeAfnemDzIFAkg==,type:str]
type: ENC[AES256_GCM,data:/NELArTE,iv:a1a6naKLosasVy/TQCmTvZp0tbUNyeEfZA+SWI91udk=,tag:oBTZ9H1EX3QKKB/ga69UwQ==,type:str]
stringData:
  values.yaml: ENC[AES256_GCM,data:d+Sy4sr1tCwOFxmjXag18bV+LdZEhb+jVqmYJq4Zk18kTbvO2yHGBtMjBAKRz5Q7RLpT8fe0243tgvP4KzojGerpkvLtwEbc41aAw7Db0tjHuCoDzePikYOr+lzWmcgMQlZWyPJyjdMMh7WsYDWse3BMKvQEMG2uRRTvQR+6SL87A56sR3ckdDXYcc6tX9bq1YQKb2Dqmxaw,iv:LHTNwhP7wpbIb1Dn4n0VuXrWKuYaTkAOr6SmWZfKhZ8=,tag:/RyKnXmftsRxHvIOL3E5hg==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVkY2akR4UGd6VFN1Qnpy
        QXBiaFE2elh0eFBKYWNXQUNjc1g1L3dqclMwClhVaEQ2aGkvVUtubHk3ZkZ0K2V5
        OUdYMXMveE5TK0U4dGlaam40MG1nVkkKLS0tIGt2cnd4TkRQTytyTlViL3djL2k1
        QTNpY2hnVHJValg0VWdPblhtYkQwWncKdAFpaitQY/k5wEodEvjirI5mKSU9ab91
        b5VWk3uoDmVdePGWpJO87a21e2/xU5QGYlFKWSKjYgruxz+emVWCjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T00:16:35Z"
  mac: ENC[AES256_GCM,data:qLiEf+f8sR8km59xHfj+AAQRhzBP/KKCT2rxD2LMwMdmMbGdrlARun8spOXdVhIqUBNUDOmaPU/d1DSnk0Yb5csUnCqxnk3FrtGmFwsVFGGILuKNU2aoU5ZhCo77rmVuX8OCBNqEEpsa/LcZ/G7S+VhcLOGowSc2k37hOp8UlpQ=,iv:Yo5IgsaqkdFfM0NjdPMDVtjTxjhorzafHxAOOEDRk9g=,tag:fIUuFqs93T2qVI9NVW5GVg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
