apiVersion: v1
kind: Secret
metadata:
  name: shelfshare-postgres-values
  namespace: shelfshare-localprod
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:wDDYvt4nkdgUqkJa92A0vB0wcAkAA8QXPq0mbCwulEjPMn/uK6s4mCPHKQb1nUfhq6k2XJG1UOx1+1MNpyYilI3PTsIqcWlSBSN39EUPQxef3bsSLIjQXY68/c3z2nGcl+87Cysj9PEG8s2RzVu3jwz3q/pLLOOCokyyU0jsP7xAfylVa5NqYsec0KfBAeR0yT2cWNARgEJc,iv:58dp7sMu/xOlzDAhSsTp2mm2BphHEvwsyqW+HGHu600=,tag:aM8fKCsZGq9gdPnUvt99mA==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJd3YwSTJ1YnRrM1dsc1NG
        VTVGY294T2xGNnhhcnBvM01lVTZFUzgzeFFJCjdBK0xwRUVoRFM0Ynh2VVc2Vkxo
        WXd4bG1tNW9JQWlnNk1zZzlqa0xXZjgKLS0tIERaN1A3clZwdTdsUklZMXFjd0NW
        bTdScWFNNk1BVDNwWWloRzhVcWRwTUEK7wwXDOBP5M+y2QAWLc3uy/XOGEveAMKu
        YKdnj6eY15VxhHdl5vYRt6dRQz4OVbqtblXkuFCSet/PbEgc4Xc9HQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T03:28:27Z"
  mac: ENC[AES256_GCM,data:RtoAzIW7+g4wbEtzsqJpU47pFEZ9hAeyL3n+fckkm9qMRnfRJH4/0EeALOWFDvrz50rqli3rtK65TVgQ/z6xOnL9+ivS4C9k/KYjnzU/AmCUXL8WtByfqyO0mW0QMNm/HBgwT/BzpC0C14rP1Bi/D/LNhIky8XX/+NMC7H99gVA=,iv:bJa7T3ENPTxsoAnNQIfysCmdYZc5y45yogPXfbDBRLU=,tag:y2bUl047hjznMBUEx2vbcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
