apiVersion: v1
kind: Secret
metadata:
  name: shelfshare-postgres-values
  namespace: shelfshare-localprod
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:isUkLkBMflXNymzxwAcjaZHGcOL7GR8yaQ55SpoHtPYnaD47Wigh/b9Z5iTq7yzcMxSHaoXvhYeSjJvIMx6iHufBe/XzsfVla4hTx5vMxfvNBPbdY0WVFrwSYnT9I7P3ErYVwZhnWCWhH5VyqSYJaqtxrl99c+LgMCP6c2oDMXlqS5cNeJ0XDyzttkhz9QQqri9hO452Ngca,iv:M3nwyaCQIMR08JEoCssQZZ8tPntWuO0zxODkR4hQZcw=,tag:K8pPQ+2+y4dTzQsmzkGfBw==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQkV0ak1ubUhNUXJKQUFW
        a1B3dytNQTA0cU5jZGRjS2xSczlnOVRPM3lrCmU1MXAvZHBRUXA5SDRUQ3FTS3J6
        RldYZmN4eEpKN1NoTTlROHN6TURJeDQKLS0tIFE0N0pUV04yZi9TdUExWXRNQ0xi
        Tjd0WWpaR1VrKzA5YXd6MGdTUHhxd1kKw5NclXzjV0X7lEauigjKvGhO9QS/XFrk
        1k221DIB+wHmb55SxKLCaRkUHkhtCZmUIfUnPQrT4dKHNNK6nZ9dXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T05:03:51Z"
  mac: ENC[AES256_GCM,data:dIlO+gX3aKH8ZC8ZXwVzGk4lHwl9xujR8k80TOXdscdJ/HUD9jwEeh/26RbpEmw6+db5inRwAKDIb0w4ZjYAahVVRzQGkHQCJvvEoZfXylU0Mwe1Iy+ANZt2nuYEaOhxIxLyxDD8P7e5VKsyqVPY7jiZryRCUXIcFcQ/NgL+so0=,iv:RDic9iHG4OL/CnTayUYa6RSg22A87CxMKAGuR57jQh4=,tag:sz8oQnubfV+D7aE5QBwCzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
