[project]
name = "shelfshare"
version = "0.1.0"
authors = [{ name = "sinaniya", email = "sinaniya@gmail.com" }]
requires-python = ">=3.13.11,<3.14.0"
dependencies = [
    "ansible>=13.0.0,<14.0.0",
    "netaddr>=1.3.0",
]
