replicaCount: 1

image:
  repository: ghcr.io/snnyvrz/shelfshare-books-service
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-credentials

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

podAnnotations: {}

resources: {}

labels:
  app: books-service

existingEnvSecret: books-service-secret

env:
  GIN_MODE: release
  TZ: UTC
