apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
  namespace: shelfshare-localprod
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/envoy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    config:
      postgres:
        host: shelfshare-postgres-postgresql
        port: 5432
