k3s_token: some-SUPER-DEDEUPER-secret-password
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb0R1Q0ZpOVJHeDkyekJ2
        U3VlRGtWemVJOWx4NUZRVksxUllYcW1lMW5vCitzbzVCZzVtS1dzUlo4bUhiU0JZ
        eExBa3lwdFQyU2ZDcnpJTEVpeEsrZTQKLS0tIGNQUU5QZ0IvaHNJWnJBL3hKQ0lH
        NW5wWkh3VWNzYXBOeEVYbk02eFo0cjAKPtG0EwIJntUGo+08PZRaqdC3MHq8qvLM
        m/rRAhJ7IHepKrUWVdSsfFbZPiV8Y8uywdEbMrCKyA3kBdRkzBnqxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T00:29:23Z"
  mac: ENC[AES256_GCM,data:HdCBbXiErNXgXazAPw6DAwm7tq0Yw4cRaCUw55x9e/HRjDcKlxpAPoUMYckmAvBfYUP+Ssaiu01LWGY3mykw1Tmv9b9go5mnH0W34/7kejM/b9LLQUQlUbMwUVKhbuFCR0jGgigsV7JVX01xdaUpIWC3o7x6zbOnBpb/VkfNi1k=,iv:V46P7hYworGLSx4lw+eCZM6PahfZfFpNKnd8FsqtBLE=,tag:XjBoVZ/yYqugXy8/rhJWgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
