k3s_token: ENC[AES256_GCM,data:DyXCBFn0nlG/bkCO7ceEh0CG1dnaD1J7sd1eT3NQ7QYDzeI=,iv:Sg0RQWnvuZwJ1S2Cq9I/cg8XV80OJVWHG2+bE8hur/Q=,tag:/m5nZ8GNhPYG9xdy9qDXfQ==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENTJPSWU0dm9WQ0x3aGZE
        YytDaDFPS0RiTDR5Q3F6RngxUHg2TVczbzJVCjh5VHNuQmFDK3lkZDBqZlhwT0Ra
        ak5VWSs3d29Ddjc4TWFOWkpLMWtEZjAKLS0tIDZCOUZhZ0NWeVIxVFZqelZuODFj
        aldEYVNML3BFQUtmT1h5UVpWK3IxdVkKvBQc8WTLQuqnoDDhmfSDsNFdfI/tIbTy
        BD1x1LFHaOUG1pt7e4fgtC4aNP/AaKRyD9OhJXRcGipRtGiK4ZXkyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T00:42:34Z"
  mac: ENC[AES256_GCM,data:6+Lg64oH5dxktQEzHpuJDPzHNsefACCz02kSu/5WmchkVtXukFNtnU+j93+91sAxlgDh0hljqLtls2EE5TJxdaVZCswO/yHM8DQjMlppEa/K56FivnPsaj7s0Ph6ezwSLnaEq35PGecqEfcOkoD3NyEBVNgL+Oxo/MtSyILrN/s=,iv:/rKAOfkGSMZVJkFZ1DOFiQnVQMp2IF8H8RE65S9kfjk=,tag:dXq0kmWPLMkysa9u+x0Xgw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
