k3s_token: ENC[AES256_GCM,data:4ux8uCBRSoX3wYAx59Akrt+QYc9k2HakGugoUaP4OiVXD+4=,iv:4NYKuW5eqEX719MDzFqgFlOxkaTlCDMbnHmO+NwCQvs=,tag:FD7gG8jBOr6jFGMCEl108A==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbVRPM1NPREp3WlY2NGlF
        dEhiaDQxZEtWYUg4dEJESG5ZYko3RjM2Z1Q0CllpcC9raXZUczFuK1ZYRHQzS2lw
        RzFnWFFhemdPQmlsTGt4T2d1bVY4RnMKLS0tIE9vekYxNkdqcEFGUjg1NGVqdXJq
        NXJQVEYrckpXUWVSQjhmcXNLYzI2cHcKnJYVwTUo4qktxYVsK9CFtdivSAmcP7oL
        aWjmFOpFH3xbHaZ75C3FRZF23Akob4S2Bm4lovSacmlxMzGoN43XuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T19:29:17Z"
  mac: ENC[AES256_GCM,data:O0ENdtkPz0FI6K2Wb5WQEs7sQXPhWVKmRZmf8i6X/U7gK4SIvuWsa6cU+BshCwvEUEQx1WGtE63+/3BHXdDkE21DfD6UAQR9WM8r3PQ8apUM0UF/YtLf0O/fFTdQzfHVdooq/jay5L7NEuVtukdcGtco06WDvg+zn9ba04gvOfU=,iv:8EQOPHVhiWNyi4inl5CuAPjGrD8yjb3fJMlkAJbjgzk=,tag:VULsl9Zd+71qxJh+Kb9u0A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
