k3s_token: ENC[AES256_GCM,data:/5uHMbrY3FYy7/H27cPEmo4mkjURdnsX8n4S4R6/xONZ3eU=,iv:Hm58ctSs+0i0ra8vLiyF81eTrhAIl1+JYDfAyyBBdlE=,tag:1/CCWMO00BMM5A7tiyg3ag==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a1NrYkRPQVJqNzdzYmJ3
        VkIwa3JaTWJOWW5GMFNqamVrVHJURlNwY2k0ClBXOVg1VkVKVlljWlRGNE1Ua2cz
        ei9QNmZsNHBqQU4yNTNaUGZoazB0L2sKLS0tIDF5d3krNTgyUytNWSsvVnd2N0U5
        ZzVhdHlGRkoreXM5MXFXUGU1OUlwK28KY+BFFmo1dmTMdAP7WeIc5wcYrHhvsYlD
        in2RgwwqnLWTPLMwzOk7Q2VupbD8im0RwKMeGijVtUSZoQTxGaFaKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T01:26:10Z"
  mac: ENC[AES256_GCM,data:xmfbttCuj1Ly+EpapgSiJcp4GPsc6uoQDJWFYPQuaPY4xzNAL1nsm+QiOkdugNEZV99E3dhR9FRvtgOC6h/jQarov/nM4RQZ3OT6SnBOiBVBqYDH02OTMLhggDZDKRqXuNGb8c/psA6QS2134gg9b+4nXtHkeXdSB480+uCVGiQ=,iv:U99mk+O8KqF4aHyeVxp7TgviCSRLiI9bc1dPgTdVVyc=,tag:PUDLFDLgRR8f232h/ykc8w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
