apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app.kubernetes.io/name: books-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: books-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
