---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: books-service
  namespace: flux-system
spec:
  image: ghcr.io/snnyvrz/shelfshare-books-service
  interval: 5m0s
  secretRef:
    name: ghcr-credentials
