apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: books-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: books-service
  policy:
    semver:
      range: "0.1.x"
