apiVersion: v1
kind: Secret
metadata:
  name: books-config
  namespace: shelfshare-localprod
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:RGD+Gks=,iv:6b1Yh9BiV8UJzg3+SyK+zj6EMrgoiCpy6zmNh4GLDWE=,tag:JwdOoQfnWbxWJibE/dzUPQ==,type:str]
  DB_PORT: ENC[AES256_GCM,data:HEa+Ig==,iv:G1yPuv6ZSHEXO2zDtFPSKdIasE+f1eb1JyVkr5QL1nY=,tag:3rHUICfTXIPZvNz2jpt09w==,type:str]
  DB_USER: ENC[AES256_GCM,data:KyFv1PwvpefyJg==,iv:22XRT03+KcTkW704AaDzjmOmLMjaoIaNiuaIdwe7+HM=,tag:D3yjNoIKWvV6FhyHE7WEKg==,type:str]
  DB_PASS: ENC[AES256_GCM,data:Q98QfZZDk2Kqe1bGUeuc/h76egiyjfwYcZdbNdcaSw==,iv:TRSAIAOs/I2o6OYWLRn0+3mb1mmEUEPkJ09bypmoL4U=,tag:KZpVcy+0+JBxyWlHyoyuOw==,type:str]
  DB_NAME: ENC[AES256_GCM,data:sH2c7BU4+1wCbA==,iv:4MBkCpS0JNDkTKfKxtw2LkK6426kD6sbCUYqjevkI7c=,tag:Y2elxNMxbk1ifgLf/R6L0A==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:LaxRp+IqAtcXpYI=,iv:nnnrrBgnlRFAG2wmD/kp5Nt2GkGuChrXB20BfHKrXyw=,tag:oX6UP6F0OhF6JyAWNILxJA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:UCA7TXR8KZGe,iv:Wklbr/7MT88A8C15zA3UUrko2UqAVte1Fm5MlJyr24g=,tag:puRkeF1YdczGK44rWeIqKw==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeU91aDZYdnZqT2xjc0FG
        NGZMRytrSThwT0d3ZjF3V0xJNk1FeGJXbVRZCjhZeUFVK2dSdnlhRjJuWnI5bHN0
        Q0lxOWhyRGlvT0FUMWZpNXU3cEM4d2cKLS0tIGFjdDNzZGgwbFZoM1R6bklrdnVt
        MGEzM0dqYlBrSDZTbW9Yc09WVi9SV0kK4h95OTHXwWLNv3js67Wt75qqOB2J34es
        JDRHluEbqdj5fHQu9TQuXgDUBQA9DEXb2I0PCzRMwrMpAWRGrgLBPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T03:28:00Z"
  mac: ENC[AES256_GCM,data:EZzT8VfHq4hvyMChMje9rBlHC80DOFTFY1Y/FbQn8Ec8P3kZgal4ksXfNT3+Y3UyIHGjjBidYXHcFqpGhe4xMaGt1ddA4yYig8m5G6I8Ng5j92QfjafKwLjuDeemP9vwGR19r9QliWGQBqsmPXFxCN5y1ltdwpZrllDToeC6T8E=,iv:zTmOD4dPxdI5ZX6Skfzvqnug07onXa8m4iNu1Rjskf8=,tag:ljZD64ptjLKsQI6PYMMIQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
