apiVersion: ENC[AES256_GCM,data:7q0=,iv:cXuCLWdztHFJkW7THMas18oyhMfrkKaTqcktO+GEUl4=,tag:l3CBdQraZCQwqMMRVQGzNQ==,type:str]
kind: ENC[AES256_GCM,data:r+B3rNjy,iv:YbVNo9kP3iCQ3+6yUM0P2MXnR1HGrhxYLq1AxaGss+M=,tag:ZJpUOjym7i+XAfWNvPiyLQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:oX2GP70F1FVU06A5,iv:r1penz8rTtN0b75vUMgJz0Jb27aOmnzuMS0wegHVh/A=,tag:E8aW9KJoPrOwMl/betMsYg==,type:str]
  namespace: ENC[AES256_GCM,data:rgnQBzysoXt1ikC27VIOYEcya3U=,iv:itiPOjukHASYCE1Bdx0LYTh+/nrDlNFTCNdzkfkFnU0=,tag:qiFZHF2NjpFH47DMgEjHrQ==,type:str]
type: ENC[AES256_GCM,data:ACyr6XVV,iv:ES8uvv7FGyU80AT0hKK+X04XU49IIe1DQnC2pYxQxSw=,tag:WBsXngCueVMV3TzOi1T1rQ==,type:str]
stringData:
  DB_HOST: ENC[AES256_GCM,data:7hFlh6o=,iv:ASnhV2MyqToeK73AXanrW8bnczITyNYC92rRuh2UZ6Q=,tag:cu11nJoZf643lTVx5I9IBg==,type:str]
  DB_PORT: ENC[AES256_GCM,data:0QoSzQ==,iv:TLIreTS7iAXoUOefkDwQ3flNkGPDsnrXw1tZLGvXjmY=,tag:k7gyNx9gT1F5MCur/1b5ZA==,type:str]
  DB_USER: ENC[AES256_GCM,data:QWp7Ph2p+fsGQw==,iv:0Cn37MtUX6ajG3Up94+1iHGq9W7nohWxR5nFwKhHgsw=,tag:BUNezr+r4xdbMWF7LChwrA==,type:str]
  DB_PASS: ENC[AES256_GCM,data:c1bYVn5LoqJAifWFI9Yz5T7O8qBJHZavAsLKpe48AA==,iv:+rjFx6SutUZoqdG4DyjrVGH/F5DI3MeSii23VQ/Kz7k=,tag:3ghBeWn+974UhbigJ6adqw==,type:str]
  DB_NAME: ENC[AES256_GCM,data:pmMll4qEcQdFcg==,iv:vKVlc3IXbtbL5W+K26yJuTYXzVAKbYp8O+d7rE0qHy0=,tag:dTriETFpj9U4eEo56g8W5Q==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:vTNquOxuyv1wcU0=,iv:Ea/u8ilrbEUod/UdeQTlnXn6rdCGniRqUGW3G2yvYrI=,tag:goyZDNuNnbJzgU6K1PPVFw==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:bLSOvqVtHObR,iv:ESVqbj5xP0GLr41CfB/0Msqc75abufE+hcxQHpnI72s=,tag:LqTcARx98RA5M+dK2jak6Q==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMXVsODlCWm9IL2dJQkFi
        T0R0dEs3RlJ3UWlHK1BhYXlhMnpjZEd0SEVrCkh5SUpmVTNRYnpWSmZCWmF2cE41
        OUlFaXhRMEcrSi9wcXJNUFgzQ1p1UkEKLS0tIHRIb2x3QTErNGRxdHlzRVdwSEsy
        eHFHZmlGcElQbERBSWU0ek1ITDNMamsKSd+DqY1UaYsF8IY4563F4WeREBlpIh2O
        mPNsQqGPjyvriceU+QiVI2NS+uPvDuQ63I6jo3APU32yBM/On61AFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T00:37:30Z"
  mac: ENC[AES256_GCM,data:1E7vM3xMeNO1ilPHFasqk8b/XTwKpLzrsPO/QwNqMbsHCN0KrGznyNv54euo7N7rlUd5PjfPknOq/F8nqyoeT/fgYSeAF2qGfAR0lGplKO6f9aqIvGKy5DPiAR9alcN3rmC0d3/0LB6G0JlSxXUIz5CX538IC0i/vP1qphtaCtc=,iv:ms3w9QpX8YBi28qm+jZtIjoTJSz0jQFtEtdzXXTF+UI=,tag:4BuvWBfawpsQzcJcvUDTHg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
