apiVersion: ENC[AES256_GCM,data:9uE=,iv:dUsVs7ahNJxu3D8rC9BI007VAJfFR3+B/vrNSJW++YA=,tag:HSakJzXrW6zxjO++I3PGZw==,type:str]
kind: ENC[AES256_GCM,data:bECywo+A,iv:tWKEUrU2VCSjTYi1fF7jdx7hHBDAL2NJ7DQUtv9yaog=,tag:mXw6102+5EL/j/NGByA0iQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:WgNc7bg+FtiJRqcYSztoiclB42g=,iv:oa473RcA42DIcjTnEwG4TRyvHQ/vYh5Qh/riDinKerQ=,tag:hrBId5D6yND+n/KDJW2Y9g==,type:str]
  namespace: ENC[AES256_GCM,data:i1KYOcHkcH9WfY2Fm08GpcZmcGg=,iv:GciE44DdBqj9bYoUm8UQkFDDRhKBf5KinPj23aXOhuc=,tag:ZV1ENDbtlTuT/b3+d+Gn8Q==,type:str]
type: ENC[AES256_GCM,data:xaMJGu5H,iv:o+uDqr10pSKt/zjE8pU0SIsW4WmL0PGJMuQPXS2aASM=,tag:hsv+I65B5vsTgs/NugFUtA==,type:str]
stringData:
  DB_HOST: ENC[AES256_GCM,data:+2eguEM=,iv:hlzOS8nlgnBWwcMZPwLs6F85KlnMziNJeDaCVKH8Rww=,tag:wxdthhImNrZMmZL7dyyNGA==,type:str]
  DB_PORT: ENC[AES256_GCM,data:IRf85Q==,iv:CGPTfXuAFzl3KSErvfVc7JNzfbKl1w1vuHkUIbl1c+A=,tag:4yxeLo+9F5BfUKO0RiQ7ag==,type:str]
  DB_USER: ENC[AES256_GCM,data:3nmqxqMHA0MKrw==,iv:NMYMIRiG38JKNVjD9uz1y3d3eNoV+7yga5EZjohqxho=,tag:NL+ceXaPqea7BWqtZiexpg==,type:str]
  DB_PASS: ENC[AES256_GCM,data:9CoEHgXYusqVmR/Z8UN69z90Fc7P4Nes6eQE82Vnrg==,iv:3JUFlmQObiLUsUQ9x+UP9s/K/Wv/2ll+2SuXQ89tViw=,tag:Ja1A4bIpVnigWjy85Jvpfw==,type:str]
  DB_NAME: ENC[AES256_GCM,data:qtkLD8g1FZgP6w==,iv:K6zXzISOJwPto0hlmUFA7xNimb2rp0LmZPtM2VzN61c=,tag:qjPge7x7AxVouDZIKJwOhw==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:17CErhxA0Q==,iv:Gv76OxEqByaw9GvKkBrqQ2Rh3zI+cu2/295kVroL8K0=,tag:xNOhYGcbFAgnnmw3ngAIHw==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:N/AKFakVamEiNu6T/L0D9KU=,iv:PxQKYIp82VON4QzRrjISkQyVDPV/9VgC/5lR4TzePmo=,tag:an9l+zuDzFK9e8SFryyrjA==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVkxPL3pMd3dqZlNOc0Z1
        Zzd2cWRHcDJRZXdIai8yU1I2OFFHSWx0UkhNCnhPbklseVI5TDZFN1BmcFAvSkUz
        aURwMGVvV0tUaFFtc1B5RjJFeVNSckEKLS0tIE5KT2pERmtnTVZjeENycHlxMTRJ
        T0ZIRGFTUWdEUitJTUQvYUxCcU9pU3cK16z495S3hot7W1En969/awwRVzqfCJtw
        Eyv6Ner9CW5BYYQ4Kve/stv6Tymcs1zZen9x0aDqPTSgXtpLNnaAkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T19:29:17Z"
  mac: ENC[AES256_GCM,data:CTPIHw8iwf/YhkwlRkF7KBDFLhQZnHMDdN03NP+xK72oXPGqeujyHBXPmJPnQPRUjFiEBQl2k9RkqW4C5jVFLSK2qik8se+H+/2h2+b4tO80MnDhD5D8jfnXWSN18zkUwGSzAJxpeEZTLDu84LDyZ8z5GDf9w0jdJOGPkMcQUpM=,iv:wOgPxHTY/OsNHRH1jFZtN0lMuUzps4er4zw1EzP4dIw=,tag:OCRaWCWcpe71OTJwdt+z8A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
