apiVersion: ENC[AES256_GCM,data:10I=,iv:EDJsfMwyNNpasP9de6saP7jILWOtBpQkzYCZjBpDzmc=,tag:JVknC4qb/QuYCdAfO1MIGQ==,type:str]
kind: ENC[AES256_GCM,data:ZFKkw92u,iv:bPTgr4QiTz2ip7QgeRSt8sehs9FJCXv+nKt62LsGShM=,tag:lJ5k+Up7rtHc7KNmT2mVMQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:9omhkQspeX1XisAvUA/NRv8YZvo=,iv:SOlQiYIbxMdJguPLeJqvEfcQR5OjRRhYzQe+YIjhNtQ=,tag:Cr81JcWM6IEeNbMbQVcpzg==,type:str]
  namespace: ENC[AES256_GCM,data:ib7yVvn1n2Gl1iEooM4pk0kYDgI=,iv:z3k1onMduIxVRllAVIoIgByegBBKF8AfJHw2J4j7qzE=,tag:tgF9wCDo01ngkftcvtRGVQ==,type:str]
type: ENC[AES256_GCM,data:jFAmrH8E,iv:z5r0PmuXgJn3Sw2YAbDpVhqwIqn24SiwEkc2Utkp0kQ=,tag:vtPwrfQ/oSq0c/2ut2F+XA==,type:str]
stringData:
  DB_HOST: ENC[AES256_GCM,data:bFPpyKQ=,iv:FolY1snalRWQe82jsdJDZFZkxhZpFKgq89V9NNcof38=,tag:v0IxYLjlyCaabCmlCFgCKg==,type:str]
  DB_PORT: ENC[AES256_GCM,data:IVk0Iw==,iv:I9wuTkRINGdb6IWV2ie6pj38K1bNAmAxQi3fB/G4l5A=,tag:OWd3Av2mXPQqd/reXzawMA==,type:str]
  DB_USER: ENC[AES256_GCM,data:Wb18CEYyzthsCw==,iv:LeD9DxQohKtNo4WjkwTj88Ny3u/s/kTBshM+sztw6bA=,tag:7muGypn4PLp7GX10HvCBmg==,type:str]
  DB_PASS: ENC[AES256_GCM,data:KZR+f2+vdTIbSAhpa3/QoYpfM6YD5I8eADTquIAtZA==,iv:tPJnOUcB2/kwkFviEZDBsR2u+PtJX4Cm/Fr70eqJh90=,tag:Q+jpz0PuO3FOU5Wc+2wFvg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:taHa3z3Zg7cSBw==,iv:xbIs4tux1HDXXr2rZ/8MwpD26mJIj6Gx88j7ZYWPX7s=,tag:UGJZeDC4MXWOR+O6zAqpKQ==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:fLkjRYMnzQ==,iv:5JAE1TR2ddZhkJPqNAiBNQWymc5aJCmffLEjBsKYmFU=,tag:BPpe4jc/xx/SFFOI4S2RcA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:SZDy26uqukYj8m5rbFzsTps=,iv:d/3nFGJhdf5Ec2GP6OTdhH1oxDn0u3xPI8epW+ZNkF0=,tag:rs7EmIljr6R1lnUaVfNtLA==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRStIUWkxZE9hdzFzNDZU
        Nk55dE5JVy8vQlNHbEpudFF4YzV4d2VUVldvCnB2bUVpc2p6OFd5SFcvMXRLODNR
        aC9LY2xWUGRVcjBuL2hENStkb1V3Q1kKLS0tIE1MU0pyOVFlQjJLZUFpQi9lTm41
        cU5mVXFTYy9OYWRlajBWWDZJREhtU0kKmegBQBqtO1x7n9xEuH4wWvqntlxvWoDO
        9Eu/z7fGj3XWdginz7uKCF+UyH5gl+SdL1DSax3RVHVOTPBdm46nIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T00:42:34Z"
  mac: ENC[AES256_GCM,data:B2mZPS95sVM3YSkUiNmnzdbPwccsROMgLgCtnm6v8fOn9QiK7Y0KUzjiPnG5fB4cwONb1rFVP5do6ScR8gGZO9dJZX8GnhfEeasXqyzGrKRxpTybvnxHRG9fKQ+Okf6pJ4axsHODIPp0OjVynqRl5xCJLHZH+27vc3PpMZD50/k=,iv:z68G1u9I0igdtW7R2XZTnvT7HAvrP2DhW4WBCPFL6yQ=,tag:/l9H8ZIBMxtLBhUM+kNQAg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
