apiVersion: v1
kind: Secret
metadata:
  name: books-service-secret
  namespace: shelfshare-localprod
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:M2im3is=,iv:0EE1RIKG84zQfpVHypovgXbMbdtwPF+DWgiY9n0t9yg=,tag:L781qLSycXaE2nOqPXL1bQ==,type:str]
  DB_PORT: ENC[AES256_GCM,data:SakqkA==,iv:cRJFAhYl0FFgZnWBRX+LakY46UTlKPTuIqdlR6GUmnA=,tag:mwTyb+5mKLJTPSv3waPkXQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:1PjiKeo8cb/DMg==,iv:bxt/2jMDmtpznkMnztgE4TdnNsv287sr1es592nappw=,tag:/CNtupJcr1KmDPVph5Tbfw==,type:str]
  DB_PASS: ENC[AES256_GCM,data:2QBgu8tndjEXFX49h91n+1bD58E5OO3mztKf2lCHCg==,iv:D/6yWaAqSi82a0X/h07erO6q5AtgebpVY4aG5+L6h3k=,tag:q0qNtvrNtJVY3Vw+58UyMg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:gNr8a2BkNX4qbw==,iv:RqZltvf8y5G3KaC6xSDsafnjHJy1qnuVOB3ki6M8qnk=,tag:6r4tFycq4vh5f9ZU9Y+VZg==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:Agd9irEXww==,iv:K9x5qX/X8gu7y5U8iecawdZIILonjR2PNRAW4PGikh0=,tag:DDUkJ8FREKggCArLPK85QA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:WTvyZcWQNGp2oLzBY+XvZ8c=,iv:qCU6TtfkQkvK+NdCD+pdfjiuXOc8pRsQQ+zZOwid2pI=,tag:NrKF/g1kjqNL0r4wp5FKxA==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2xOajlGeUQwWkVlWUQv
        WWdWRC9DUnE1Z1hxdkdnYVp3NzdBdFU5UnlnCklNV0l4d09VOU0vZmYxQS83aXEx
        bnp6WlBzTUdlb1lnb0Q3RWtjVUYxdUEKLS0tIGNnaFY3WXNWdmhjS3ZlWHp1NzdE
        R2VqdTZZUkNYdnlzbCt5NjBIV3BLT2cKDeo8Nz1VcKzob5nRmTlEfgmXqF5gni33
        G3WpmdmHdmgXfVzQUSwkLhb7aWQGb1HPtMliL7mE2yDTNq/49ZW9zQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T18:52:21Z"
  mac: ENC[AES256_GCM,data:O8/mItnbI7c5hNHkzu1A/EBt7Rr4x7RdiLrn2iikmFus8WxpYCPTSAf8LtfWFMpHs0gRvv7qgueEtHoWsKw1Nj2Iz/Ta8oczy+8CZJq/8ryBlO9k/mU36mWHJ8Y6w64cIApUpKF2tJVO+VkF8e5TrryntY7NVhpfsyIGzCR2j0o=,iv:qBGfsMkM1eqNeWxmR2IN1o1iUSuKgjwwifLDGgxFdFM=,tag:+RsoBtPAMEOP+T30TIcNIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
