apiVersion: v1
kind: Secret
metadata:
  name: books-service-secret
  namespace: shelfshare-localprod
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:n2RhC1A=,iv:xHSCvSRwyviV8TFU6CV0SC5uPPXuj7p5q2iy+tTGPuE=,tag:ZcZevIkRMpGErfdRdsD+6w==,type:str]
  DB_PORT: ENC[AES256_GCM,data:POCaqg==,iv:Nyv7BK42w8IsmbE1E7h+1UG1YnMize0KmyVEKc6tZro=,tag:i8D0BLx+xTSi13L+T/NJmQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:CMpJxVUrf7BbQw==,iv:dMWYG8QLrWONjSjWh4tbTvJolQMaToiUxIyYKNJFj34=,tag:I7pAYEgiBTyH3CA1x4RFGA==,type:str]
  DB_PASS: ENC[AES256_GCM,data:vsUGqLGCY1ITnsfQzud5szddZkA36IEmTBKgI2EiPw==,iv:hIt5pDfrBkosrlfsL1P10LWj0hVRqkUg5QJzq7MUSdo=,tag:EvoofqcUyvh62bDZPCx9hg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:KdgDv/R3DJhwEw==,iv:saCtr/FVl+eEseWebuRrvRM7uN7NmyTeww9UFZLD9fQ=,tag:01yglkHa9pkqObW7PuzPCg==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:UA6RVgkkkA==,iv:4O8gkUN/8kDvHa306hoxTfpsBPk3OEhxOXYP6sFs018=,tag:/bRI6q0sTwBRJJkARYzQLA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:fdnDFjNwUeYQJfRrtH38ocg=,iv:9rC3lm2hSWJrTEgcl0lGOAzVtFAYSkh3Y1LDxT+MmI8=,tag:CgGSlfJddCJNmF672qs3rA==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRHkrTlJUTnAwYUZlOUlN
        Y3FUM01SZHpLMXZ3VlpnSGVaSXdMRTN1UUI4Cm1wN1Vtc1RtM3Mxd2FCdVJiRHUr
        RGpMTEdSSWZrcTcyc2lsb0lvVUJsQkkKLS0tIFZTSFNxOTUzUHB6KzlTcTVFWDFO
        Y213NXcyQmNNbkVqTVB4b1JoUXc5d2sKLdGXMuaRxhoJG/i27rXQ3u6wGnmQ6oGk
        BZxTAqQmU8ZJnLb0NCqFI3+G2ntYvJUWkG7ZjMuxEDr5ySZqU9u7dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T05:03:51Z"
  mac: ENC[AES256_GCM,data:wW6Nt4yNi/q5moi+zfjJV+oNDDF0czqDmksSliYttmuMM5zz38/L2hwPdybQqnwrWAM8KrB+Zeyac16uKOod/cdGoT6TIGAm2WMHaqW56H4HKuwZw1g4YoXsbW9VG4LbNdwYZ7RZfHJsJg3pHGRumF0T0YAMdI4DL9WhtvnvH5E=,iv:rNQZa0CUDACxla2kfy97NKkMqJ3UgAKSPZxhV5Pq008=,tag:Tx1dRjuaRaKriOhFGR92rA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
