apiVersion: v1
kind: Secret
metadata:
  name: books-service-secret
  namespace: shelfshare-localprod
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:S+H3hD326wcDKjbbo0Ad9DNjdKqlzcd+XZOy34IQ,iv:1QHxFd1P4WPnz3Auobv4c3utnVWj87ep9/97x/wcPGQ=,tag:AV3wz/rtZD8MKP0A09WxbA==,type:str]
  DB_PORT: ENC[AES256_GCM,data:rJ60Bw==,iv:acI1Xvjf/0CuIqYWiFoDiqw2qRtgrrpksN1Eevi06Ao=,tag:6vQIui4/EAfHVacg6XKGNA==,type:str]
  DB_USER: ENC[AES256_GCM,data:ppoa5P064+0=,iv:A3VCKQoFH40AR5Tu81H4pLUd+ubptb1sLMK5L1S45eE=,tag:OV/2EvkI8cUoxbEFMcxzoA==,type:str]
  DB_PASS: ENC[AES256_GCM,data:Z6iPrqardWMr7rCzaw==,iv:1XDrUGEOSB091OEL6f/dkbnUAMCthSZVXf+Xajql9kU=,tag:Fsxk2dnvD/1tqB+qfGfHWg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:TDwPY13hC9EUrg==,iv:Kqu+sZBS3+sEE40LrZ34LS0zEG7cywyVteTL/dCXEoY=,tag:B4FMKrpT+rvgHZGPX+Xh8Q==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:6qrwhcnfjQ==,iv:tnvMbh18TkBCsHoqRL/UCggLfoLE2v5E7Ipaw7r3HJ0=,tag:cS595ZBJnPVIZdWKtcdLJw==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:sOcLUvsJ7PlItLMsD5ve3aJ1yQ==,iv:EOS5m6yyjlVGXN1kW8hnzW21frHlnilRr5ClgFciktY=,tag:UvDbpHV+OLuIGXmcvPJGkQ==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMENNVlEvbWJ2TFVtSmVU
        UkQ2K2d5NUtocHZuVFRjVlpsc0pHSmpHenpFClZQOCtEcDhYL1ZneTd6RUtZalBC
        aDROL3Z4am90TGJIZys2ekF5aG5rY2cKLS0tIHFhUEdtVlZoN1BnRjY0ZjJDSnlQ
        Vm9kRFMzUzhhZkR5enVuTFlpWG0rUTgKcX2d74GpHuI2W1VvDaXOcU3gUF61u4HZ
        1oF0hbXY+cBvBj3OJ71yyno8NMddY41ItOe8t0X81vFO4pjRiusRLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T14:24:01Z"
  mac: ENC[AES256_GCM,data:plPj/cwfVpTa5/us6ck/8VxqTZdBr0iWVCw2Cf1A6KyE0NJYb6ZNsnTCHumhcnd4LV+0CYHkqc+K7e3RumfW31j0dklRvNYz72VGC+uvZPjt5VjEgp29EunP2JHff2rsteObVQmDqoCxtf6A0MSkTaRJbb4ceVIsk5b0AbrcpOs=,iv:aqaGrirJyLqqBgsAGKTosZLVOCl+5HaQiVQvL/kuHqE=,tag:mxzhSTwmcMSF2r/Ug9MmHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
