apiVersion: v1
kind: Secret
metadata:
  name: books-service-secret
  namespace: shelfshare-localprod
type: Opaque
stringData:
  DB_HOST: ENC[AES256_GCM,data:M2im3is=,iv:0EE1RIKG84zQfpVHypovgXbMbdtwPF+DWgiY9n0t9yg=,tag:L781qLSycXaE2nOqPXL1bQ==,type:str]
  DB_PORT: ENC[AES256_GCM,data:SakqkA==,iv:cRJFAhYl0FFgZnWBRX+LakY46UTlKPTuIqdlR6GUmnA=,tag:mwTyb+5mKLJTPSv3waPkXQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:CaNJZ86EiIg=,iv:itjwVWSS3s4Or61CaeWyWs80R0H6fkxNXBYJjrp/CdU=,tag:qrNM+xgkd8shRzz1E7/EqQ==,type:str]
  DB_PASS: ENC[AES256_GCM,data:6KJ0OhwTBQWwlw==,iv:8ArDcDZkFyHbMkryFPS6UgXyxlWdP/2F52GkYvhRI3U=,tag:ZAJlqWe3XAXo5FvLIQJ9zA==,type:str]
  DB_NAME: ENC[AES256_GCM,data:gNr8a2BkNX4qbw==,iv:RqZltvf8y5G3KaC6xSDsafnjHJy1qnuVOB3ki6M8qnk=,tag:6r4tFycq4vh5f9ZU9Y+VZg==,type:str]
  DB_SSLMODE: ENC[AES256_GCM,data:Agd9irEXww==,iv:K9x5qX/X8gu7y5U8iecawdZIILonjR2PNRAW4PGikh0=,tag:DDUkJ8FREKggCArLPK85QA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:WTvyZcWQNGp2oLzBY+XvZ8c=,iv:qCU6TtfkQkvK+NdCD+pdfjiuXOc8pRsQQ+zZOwid2pI=,tag:NrKF/g1kjqNL0r4wp5FKxA==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2xOajlGeUQwWkVlWUQv
        WWdWRC9DUnE1Z1hxdkdnYVp3NzdBdFU5UnlnCklNV0l4d09VOU0vZmYxQS83aXEx
        bnp6WlBzTUdlb1lnb0Q3RWtjVUYxdUEKLS0tIGNnaFY3WXNWdmhjS3ZlWHp1NzdE
        R2VqdTZZUkNYdnlzbCt5NjBIV3BLT2cKDeo8Nz1VcKzob5nRmTlEfgmXqF5gni33
        G3WpmdmHdmgXfVzQUSwkLhb7aWQGb1HPtMliL7mE2yDTNq/49ZW9zQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T16:31:24Z"
  mac: ENC[AES256_GCM,data:/V8ZC6j8esaIKIBUSHkGOplQ81AlnDqNIPQaA1glAuPLrpRiXTHj4eMXkqiDdAU8titMAhOHqplUCEtksermZn70nwtl0rQCnbpzbYM22/5jVaXZobs86WyNhjO7ebchyCWE2dXDiHOjk4d0OT59SKGBhQbDkSrk89rGtInfasw=,iv:7n8nyKx8J68JwtNKbxD95UxMI0e6t2YPjUhuBdmGLRg=,tag:mQw/rgazIM4vZjy1N8jXsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
