apiVersion: v1
kind: Secret
metadata:
  name: traefik-values
  namespace: shelfshare-localprod
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:REaraBeTI3Xg7msaO3HkWlxufoox4do7OrRDfA8TNbe3go2zBVubYsDtOa30aH3e0wIIRRjIi/JrBlu3RWD8bAXTFcLcvTcMTLenXrns5gknDNdafvBR7Fd03TsQ8FpaetPvA8hyFlmpFfDM3i/pVqhm,iv:45gUIrSa6iw1CvOyl/AMxQGlPkk/QEt35SxZclfqoPA=,tag:MvOzNC7c+AiNZOq5tTNoNQ==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ3ZneHU2di94VnhmNUdM
        ZFBlQzV5TXhtbW8yU1l6YS9DOWRRcVBIY25BCkRyYzd6K09TSlFKZ3kyVnMwenZi
        d2dRUEkvVmRqR2xBTVQ1T0hVRkdwdUkKLS0tIFdPTlM2d01YUDlmV1RSNmlpZ3Qx
        OEhucEJhb1ZtdTNISENDMzZCRHRsL1EKzt3EFutF3MlH1iAS3+xY/dGk/VrJmoUc
        j83hdpEhHgVA6CLcuuEIGd7gtGSiJZ85LvurcGvRq+EC7JAZBbEv1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T03:29:00Z"
  mac: ENC[AES256_GCM,data:rpsOtg17N954gJVduRB+uQbjfVZNRHZ3RKPgMa50lfXxtDCdUn3FoofbSg2HXC3s6wlqiQBsP4nR8/MMQ009+Z6+boIT+yMyvFU1qudD0IvFcLg/63UqkRh/B9tyqEpcJ1DCJiHUNL5/SKoeNKSENYpc9OydFpgnLGluY2P7GXg=,iv:5UrGh/v7kqRE09fU8cl/2x61QQdL36juMKI9LkKgfBA=,tag:uJT/LyfEz110yhlC9kc4jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
