apiVersion: ENC[AES256_GCM,data:v3c=,iv:glzM1xr/fa+Ak+3K/LsLKM9TawrAfut79evh/FoxGu4=,tag:ZOCep8DfQzrnyogV2ytQGg==,type:str]
kind: ENC[AES256_GCM,data:yH0uxokl,iv:r0j2N2hKsoKreHJ5We+jH0oOiJa+3BDxKVVwymgIgqU=,tag:7S6U5UQvJ6md+8H3wzlLAQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:4ZQlYMdDWB3BSpawAvQ=,iv:T6Qu7FYGOzDLC9My7sDI80fE6oWDmqSQ6x75RXhpGSs=,tag:g/1qysfFAtQer4ETYbDzBg==,type:str]
  namespace: ENC[AES256_GCM,data:acQzdbVSqXVuzUG/76HNS/NMWLg=,iv:LOcE4JvImYdvL0U8v7jsXpij3wDulDfqTJcRfw2MxQY=,tag:Heh8V70/yfBhV9AY8hU5Fw==,type:str]
type: ENC[AES256_GCM,data:UCrUtqKe,iv:LrDVtCdI1qgzcqqFh59FWx/BZeBR1mRDlPCHuPrpfX8=,tag:hqgRqdws5Gz9YOYTsVedbQ==,type:str]
stringData:
  values.yaml: ENC[AES256_GCM,data:CgucYfhnN/JPKGMQu+P20FVaedSzncLsOve8W6BOyQrdXCs3r2cn/OB/WhovHgVP36qJ2K8l2tH87GqOo8ufTp9kMd+A2KcqXUbELiAnDSmJ4nzqN5G15xGdwPwmU83iyd6UkXzV3OQaLihSfmKqT20+,iv:4pG4DeimTG47sHfyb+Rzd401mqSmg592sOJZFa/vjbc=,tag:a7vuw5UUY8pbk2T9Rq4Shw==,type:str]
sops:
  age:
    - recipient: age1rg7x2x9azaxn7j5tht9tkne7lhtd2ajzevu7dlgaqr0f4enlwygste5dep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUmVoeHFCbFBvUUEwaEpY
        L1VBYmh0T1kyRUt0U09BY2swS08weTlMTkZVCkxTOE9tVHNyRWs5RlpFYlNLbHVE
        SHBzWTlqTCtaS2QzR2NETmFjaDhsSU0KLS0tIG90MmNrd0ozb0pBcVYrVldMM2tQ
        bDI5WlFYWVRiUjV4RVlVV28wK21ic00K1tctiSIQGCQFDU13MepVS5hPLb8qOKms
        3uc8fmsygT0uhDYttrAiOZ/YALnviAWbb9y8AlbdS04YwLChitubwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T19:29:17Z"
  mac: ENC[AES256_GCM,data:EMsTFYa0nA1azS9U+7vq194iucHILuSEo43dHXSYLcXCuLrlsGpPGwVqxCZ4FkvN52zLjh+yLdar6zY3idfR4rg7e5PT+17oZ4Xq+kBzlHlKmkGUCDlQhn62JcpbGdahR32uhLfL1fmbhJt7AzDvKtz1a5bJjSH6jWpC/Q79BZc=,iv:TudFkMnjYtt30fQnTcTeSarmGy6Acx4Rxsm0Uy9QJmY=,tag:Ak/3LB3UTQqQuzrtbA9RGg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
