apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "envoy.fullname" . }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "envoy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "envoy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-c"
            - "/etc/envoy/envoy.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "envoy.fullname" . }}-config
            items:
              - key: envoy.yaml
                path: envoy.yaml
